### ISSUE TITLE
not working on django 1.11.x

### ISSUE THREAD

**Issue by roryrjb** [fabiocaccamo/django-colorfield#39]
The exception raised is:

```
'ColorWidget' object has no attribute 'template_name'
```

...everything was working just fine in `v1.10.x`. It appears the widget API changed from `v1.11.0` onwards, see https://docs.djangoproject.com/en/2.0/ref/forms/widgets/#django.forms.Widget.get_context, noting the sections highlighted with __New in Django 1.11.__

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?
